package General;

public enum Request {
    SIGN_IN, SIGN_UP, BACK, EXIT, CONTINUE, SEND_USER,
    NEW_GAME_ACCEPT, GET_USERS_TO_STRING, NEW_GAME_REQUEST, Confirmation, SIGN_UP_KEY, IN_GAME,MOVE,
    GET_GAME_REQUESTS
}
